baseURL = "https://hi.tokenisite.top/"
title = "æ¡¶è£…å¹ºè›¾å­"
theme = "CratMod"
copyright = "ä½¿ç”¨ CC0 åè®®ï¼Œå…è®¸æ‚¨è‡ªç”±ä½¿ç”¨"
languageCode = "zh"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
pygmentsUseClasses = true

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "æ¡¶è£…å¹ºè›¾å­"
fancyTitle = "ğŸ” æ¡¶è£…å¹ºè›¾å­"
description = "418 I'm a teapot"
author = "è¯å…ƒ"
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = true
ShowReadingTime = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = true
disableScrollToTop = false
hidemeta = false
hideSummary = false
comments = true
showtoc = true
tocopen = false

[params.assets]
favicon = "/favicon.ico"
favicon16x16 = "/favicon.ico"
favicon32x32 = "/favicon.ico"
apple_touch_icon = "/favicon.ico"
safari_pinned_tab = "/favicon.ico"
banner = "/banner.png"

[params.homeInfoParams]
Title = "æ¡¶è£…å¹ºè›¾å­"
Content = "418 I'm a teapot"

[[params.socialIcons]]
name = "github"
url = "https://github.com/tokenicrat"

[[params.socialIcons]]
name = "email"
url = "mailto:tokenicrat@tokenisite.top"

[params.cover]
hidden = false
hiddenInList = false
hiddenInSingle = false

[[menu.main]]
identifier = "home"
name = "ğŸ“š æ¡£æ¡ˆ"
url = "/archives/"
weight = 10

[[menu.main]]
identifier = "categories"
name = "ğŸ“‚ åˆ†ç±»"
url = "/categories/"
weight = 15

[[menu.main]]
identifier = "tags"
name = "ğŸ·ï¸ æ ‡ç­¾"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "about"
name = "ğŸ§ å…³äº"
url = "/about/"
weight = 30

[markup.highlight]
noClasses = false
guessSyntax = false
lineNos = true
